version: '3.7'
services:
  valkyrie-rest:
    container_name: valkyrie-rest
    build:
      context: .
    image: valkyrie-rest:1
    ports:
      - "80:80"
      - "5000:5000"
    volumes:
      - ./source:/usr/src/app
    depends_on:
      - valkyrie-db
    env_file:
      - ./env_files/config.env
    # stdin_open: true
    # tty: true

  valkyrie-db:
    container_name: valkyrie-db
    image: mysql:8.0.3
    volumes:
      - ./data/datastore:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dancer
      - MYSQL_DATABASE=valkyrie
      - MYSQL_USER=sandra
      - MYSQL_PASSWORD=dancer